name: Setup environment

inputs:
  solana:
    description: Install Solana if `true`. Defaults to `false`.
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Set Environment Variables
      shell: bash
      run: pnpm zx ./scripts/ci/set-env.mjs

    - name: Install Solana
      if: ${{ inputs.solana == 'true' }}
      uses: solana-program/actions/install-solana@v1
      with:
        version: ${{ env.SOLANA_VERSION }}
        cache: true
